[platformio]
default_envs = pzem-teste

[base_para_projeto]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.30-2/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

build_type = release
upload_speed = 115200
monitor_speed = 115200

build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
	-Os
	-Wl,--gc-sections

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_upload.before_reset = usb-reset


; =========================
; TESTE INICIAL DO PZEM
; Compila apenas teste_PZEM.cpp
; =========================
[env:pzem-teste]
extends = base_para_projeto

; Se quiser forçar a porta, descomente:
; upload_port = COM5
; monitor_port = COM5

build_src_filter =
	-<*>
	+<teste_PZEM.cpp>

lib_deps =
	mandulaj/PZEM-004T-v30@^1.1.2


; =========================
; PROJETO FINAL
; Compila measurement.cpp + servidor.cpp
; =========================
[env:projeto-final]
extends = base_para_projeto

; Se quiser forçar a porta, descomente:
; upload_port = COM5
; monitor_port = COM5

build_src_filter =
	-<*>
	+<measurement.cpp>
	+<servidor.cpp>

lib_deps =
	mandulaj/PZEM-004T-v30@^1.1.2
	esp32async/ESPAsyncWebServer@^3.11.1
	esp32async/AsyncTCP@^3.4.10
	knolleary/PubSubClient@^2.8
	256dpi/MQTT@^2.5.2
	bblanchon/ArduinoJson@^7.0.4


; =========================
; PROJETO FINAL COM MATTER
; Compila apenas measurement2.cpp
; =========================
[env:projeto-final-matter]
extends = base_para_projeto

; Se quiser forçar a porta, descomente:
; upload_port = COM5
; monitor_port = COM5

build_src_filter =
	-<*>
	+<main.cpp>
  +<measurement.cpp>

lib_deps =
	eatingjan1/arduino-esp32-matter-extra-endpoints@^1.1.2
	knolleary/PubSubClient@^2.8
	256dpi/MQTT@^2.5.2
	bblanchon/ArduinoJson@^7.0.4
	mandulaj/PZEM-004T-v30@^1.1.2